module:
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  comment: 0
  config: 0
  config_filter: 0
  config_split: 0
  ctools: 0
  datetime: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  file: 0
  filter: 0
  graphql: 0
  graphql_core: 0
  graphql_permissions: 0
  graphql_upload: 0
  help: 0
  image: 0
  language: 0
  link: 0
  locale: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  node: 0
  nsc_columnists: 0
  nsc_core: 0
  nsc_layouts: 0
  nsc_metatags: 0
  nsc_user: 0
  nsc_user_profile: 0
  options: 0
  page_cache: 0
  path: 0
  profile: 0
  rules: 0
  serialization: 0
  shortcut: 0
  subrequests: 0
  switch_page_theme: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  typed_data: 0
  update: 0
  user: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  publication_date: 99
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  nsc: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: pt-br
