session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    pt-br: ''
    en: en
  domains:
    pt-br: ''
    en: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
langcode: pt-br
